### PR TITLE
Cicd-system

### PR DESCRIPTION
**Pull request by dobefore**
refer to #19. 
Currently 2 targets are met.
- [x] action on pull request.automatically run build/clippy/fmt/test commands for windows/linux/macos respectively
- [x] action on draft relese .build binaries for linux-arm(static),windows/linux(dynamical)/macos after local tag is pushed 

whether all builds are static-linked or not depends on test binary afterwards.

Thus far,I just think of two aspects for the system.
Much appreciated if you can give some advice.@redmie,thanks.

### CODE REVIEW

**Comment by dobefore** [comment]
thanks,those are great ideas!I made changes as follows:

- [x] add pre-commit operation before runing building in ci.yml
- [x]  modify release package name,take version 0.1.3 for example,
```
armv7:ankisyncd_0.1.3_armv7_muslc.tar.gz
;linux:ankisyncd_0.1.3_x86_64_glibc.tar.gz
;macos: ankisyncd_0.1.3_macOS_x86_64.zip;
```
- [x] run script clone_patch_anki  to clone and patch anki library  after running pre-commit in ci.yml and before starting building procedures.

**Comment by redmie** [comment]
I think precommit is failing as it runs cargo check to see if the prjects build but anki library is missing as such we should be running `clone_patch_anki` before running pre-commit.

Apart from that this MR is really good!

**Comment by dobefore** [comment]
Hi@redmie,When running clone_patch_anki script on macos,error appears`./scripts/clone_patch_anki: line 7: realpath: command not found` it seems there is not environmental variable like `realpath`.

Do you think it;s ok writing script clone_patch_anki in Python to avoid such problems?

**Comment by dobefore** [comment]
Because CI system works normally,I will merge this.Next step I will try to test draft release

**Pull request merged**
